AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Description: The ID of the VPC where the ECS cluster and tasks will be deployed.
    Type: String

  PrivateSubnets:
    Description: Comma-separated list of private subnet IDs for the ECS tasks.
    Type: CommaDelimitedList

  MongoRootUsername:
    Description: MongoDB root username.
    Type: String
    NoEcho: true

  MongoRootPassword:
    Description: MongoDB root password.
    Type: String
    NoEcho: true

  MySqlRootPassword:
    Description: MySQL root password.
    Type: String
    NoEcho: true

Resources:
  # EFS File System for MongoDB and MySQL
  MongoEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true

  MySqlEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true

  LogGroupMysql:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/MongoMySqlTask
      RetentionInDays: 14
      Tags:
        - Key: Name
          Value: LogGroupMysql

  LogGroupMongo:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/MongoMySqlTask
      RetentionInDays: 14
      Tags:
        - Key: Name
          Value: LogGroupMongo
          
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # Task Definition
  MongoMySqlTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MongoMySqlTask
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "512"
      Memory: "2048"
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: mongodb
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mongodb:latest
          PortMappings:
            - ContainerPort: 27017
          Environment:
            - Name: MONGO_INITDB_ROOT_USERNAME
              Value: !Ref MongoRootUsername
            - Name: MONGO_INITDB_ROOT_PASSWORD
              Value: !Ref MongoRootPassword
          MountPoints:
            - SourceVolume: mongo-data
              ContainerPath: /data/db
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/MongoMySqlTask
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecsmongo
        - Name: mysql
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mysql:latest
          PortMappings:
            - ContainerPort: 3306
          Environment:
            - Name: MYSQL_ROOT_PASSWORD
              Value: !Ref MySqlRootPassword
          MountPoints:
            - SourceVolume: mysql-data
              ContainerPath: /var/lib/mysql
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/MongoMySqlTask
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecsmysql
      Volumes:
        - Name: mongo-data
          EFSVolumeConfiguration:
            FilesystemId: !Ref MongoEFS
            RootDirectory: "/mongo"
        - Name: mysql-data
          EFSVolumeConfiguration:
            FilesystemId: !Ref MySqlEFS
            RootDirectory: "/mysql"
      Tags:
        - Key: Name
          Value: MongoMySqlTask

  # ECS Service
  MongoMySqlService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref MongoMySqlTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref TaskSecurityGroup
      Tags:
        - Key: Name
          Value: MongoMysqlService


  # Security Group for ECS Tasks
  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to MongoDB and MySQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 10.0.0.0/20
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/20
      Tags:
        - Key: Name
          Value: TaskSecurityGroup

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
  MongoEFSId:
    Value: !Ref MongoEFS
  MySqlEFSId:
    Value: !Ref MySqlEFS
