AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate with MySQL and MongoDB using EFS for persistent storage, CloudWatch Logs, and ECR VPC Endpoint

Parameters:
   VpcId:
      Type: AWS::EC2::VPC::Id
      Description: The VPC ID where the ECS cluster will be deployed
   PrivateSubnet:
      Type: AWS::EC2::Subnet::Id
      Description: Private Subnet for ECS Tasks
   PublicSubnet:
      Type: AWS::EC2::Subnet::Id
      Description: Public Subnet ID

   MongoUsername:
      Description: MongoDB root username.
      Type: String
      NoEcho: true

   MongoPassword:
      Description: MongoDB root password.
      Type: String
      NoEcho: true

   MySqlRootPassword:
      Description: MySQL root password.
      Type: String
      NoEcho: true

Resources:
   ECSCluster:
      Type: AWS::ECS::Cluster
      Properties:
         ClusterName: DBFargateCluster

   EFSFileSystem:
      Type: AWS::EFS::FileSystem
      Properties:
         PerformanceMode: generalPurpose
         ThroughputMode: bursting

   EFSAccessPointMySQL:
      Type: AWS::EFS::AccessPoint
      Properties:
         FileSystemId: !Ref EFSFileSystem
         PosixUser:
            Uid: "1000"
            Gid: "1000"
         RootDirectory:
            CreationInfo:
               OwnerUid: "1000"
               OwnerGid: "1000"
               Permissions: "0755"
            Path: "/mysql"

   EFSAccessPointMongoDB:
      Type: AWS::EFS::AccessPoint
      Properties:
         FileSystemId: !Ref EFSFileSystem
         PosixUser:
            Uid: "1000"
            Gid: "1000"
         RootDirectory:
            CreationInfo:
               OwnerUid: "1000"
               OwnerGid: "1000"
               Permissions: "0755"
            Path: "/mongodb"

   EFSMountTarget:
      Type: AWS::EFS::MountTarget
      Properties:
         FileSystemId: !Ref EFSFileSystem
         SubnetId: !Ref PublicSubnet
         SecurityGroups:
            - !Ref EFSSecurityGroup

   EFSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: Security group for EFS
         VpcId: !Ref VpcId
         Tags:
            - Key: Name
              Value: rs-apps-0-efs-sg

   ECSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: Security group for ECS Tasks
         VpcId: !Ref VpcId
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-sg

   EFSSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
         GroupId: !Ref EFSSecurityGroup
         IpProtocol: tcp
         FromPort: 2049
         ToPort: 2049
         SourceSecurityGroupId: !Ref ECSSecurityGroup
         Tags:
            - Key: Name
              Value: rs-apps-0-efs-sg-ingress

   EFSSecurityGroupEgress:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
         GroupId: !Ref EFSSecurityGroup
         IpProtocol: tcp
         FromPort: 2049
         ToPort: 2049
         DestinationSecurityGroupId: !Ref ECSSecurityGroup
         Tags:
            - Key: Name
              Value: rs-apps-0-efs-sg-egress

   ECSSecurityGroupIngressRuleMySQL:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
         GroupId: !Ref ECSSecurityGroup
         IpProtocol: tcp
         FromPort: 3306
         ToPort: 3306
         CidrIp: 0.0.0.0/0
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-sg-ingress-mysql

   ECSSecurityGroupIngressRuleMongoDB:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
         GroupId: !Ref ECSSecurityGroup
         IpProtocol: tcp
         FromPort: 27017
         ToPort: 27017
         CidrIp: 0.0.0.0/0
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-sg-ingress-mongodb

   ECSSecurityGroupEgressRule:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
         GroupId: !Ref ECSSecurityGroup
         IpProtocol: tcp
         FromPort: 2049
         ToPort: 2049
         DestinationSecurityGroupId: !Ref EFSSecurityGroup
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-sg-egress


   ECSExecutionRole:
      Type: AWS::IAM::Role
      Properties:
         AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
               - Effect: Allow
                 Principal:
                    Service: ecs-tasks.amazonaws.com
                 Action: sts:AssumeRole
         ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
            - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
            - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess 
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-execution-role

   ECSTaskRole:
      Type: AWS::IAM::Role
      Properties:
         AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
               - Effect: Allow
                 Principal:
                    Service: ecs-tasks.amazonaws.com
                 Action: sts:AssumeRole
         ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
            - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
            - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess 
         Tags:
            - Key: Name
              Value: rs-apps-0-ecs-task-role

   MySQLTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
         Family: mysql
         NetworkMode: awsvpc
         Cpu: "256"
         Memory: "512"
         RequiresCompatibilities:
            - FARGATE
         ExecutionRoleArn: !Ref ECSExecutionRole
         TaskRoleArn: !Ref ECSTaskRole
         ContainerDefinitions:
            - Name: mysql
              Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mysql:latest
              Essential: true
              PortMappings:
                 - ContainerPort: 3306
                   HostPort: 3306
              Environment:
                 - Name: MYSQL_ROOT_PASSWORD
                   Value: !Ref MySqlRootPassword
              LogConfiguration:
                 LogDriver: awslogs
                 Options:
                    awslogs-group: !Ref CloudWatchLogsGroup
                    awslogs-region: !Ref AWS::Region
                    awslogs-stream-prefix: mysql
              MountPoints:
                 - SourceVolume: mysql-storage
                   ContainerPath: /var/lib/mysql
         Volumes:
            - Name: mysql-storage
              EFSVolumeConfiguration:
                 FileSystemId: !Ref EFSFileSystem
                 TransitEncryption: ENABLED
                 AuthorizationConfig:
                    AccessPointId: !Ref EFSAccessPointMySQL

   MongoDBTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
         Family: mongodb
         NetworkMode: awsvpc
         Cpu: "256"
         Memory: "512"
         RequiresCompatibilities:
            - FARGATE
         ExecutionRoleArn: !Ref ECSExecutionRole
         TaskRoleArn: !Ref ECSTaskRole
         ContainerDefinitions:
            - Name: mongodb
              Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/mongodb:latest
              Essential: true
              PortMappings:
                 - ContainerPort: 27017
                   HostPort: 27017
              Environment:
                 - Name: MONGO_INITDB_ROOT_USERNAME
                   Value: !Ref MongoUsername
                 - Name: MONGO_INITDB_ROOT_PASSWORD
                   Value: !Ref MongoPassword
              LogConfiguration:
                 LogDriver: awslogs
                 Options:
                    awslogs-group: !Ref CloudWatchLogsGroup
                    awslogs-region: !Ref AWS::Region
                    awslogs-stream-prefix: mongodb
              MountPoints:
                 - SourceVolume: mongodb-storage
                   ContainerPath: /data/db
         Volumes:
            - Name: mongodb-storage
              EFSVolumeConfiguration:
                 FileSystemId: !Ref EFSFileSystem
                 TransitEncryption: ENABLED
                 AuthorizationConfig:
                    AccessPointId: !Ref EFSAccessPointMongoDB


   CloudWatchLogsGroup:
      Type: AWS::Logs::LogGroup
      Properties:
         LogGroupName: /ecs/my-fargate-cluster
         RetentionInDays: 7


   MySQLService:
      Type: AWS::ECS::Service
      Properties:
         Cluster: !Ref ECSCluster
         TaskDefinition: !Ref MySQLTaskDefinition
         DesiredCount: 1
         LaunchType: FARGATE
         NetworkConfiguration:
            AwsvpcConfiguration:
               Subnets:
                  - !Ref PublicSubnet
               SecurityGroups:
                  - !Ref ECSSecurityGroup
               AssignPublicIp: DISABLED

   MongoDBService:
      Type: AWS::ECS::Service
      Properties:
         Cluster: !Ref ECSCluster
         TaskDefinition: !Ref MongoDBTaskDefinition
         DesiredCount: 1
         LaunchType: FARGATE
         NetworkConfiguration:
            AwsvpcConfiguration:
               Subnets:
                  - !Ref PublicSubnet
               SecurityGroups:
                  - !Ref ECSSecurityGroup
               AssignPublicIp: DISABLED

Outputs:
   ECSClusterName:
      Description: The name of the ECS Cluster
      Value: !Ref ECSCluster
   EFSFileSystemId:
      Description: The ID of the EFS File System
      Value: !Ref EFSFileSystem
   MySQLServiceName:
      Description: The name of the MySQL ECS Service
      Value: !Ref MySQLService
   MongoDBServiceName:
      Description: The name of the MongoDB ECS Service
      Value: !Ref MongoDBService
   CloudWatchLogsGroupName:
      Description: The name of the CloudWatch Logs Group
      Value: !Ref CloudWatchLogsGroup
